### PR TITLE
Add setuptools to install dependency

### PR DESCRIPTION
**Pull request by davide-f**
### What does this PR do?
Fixes Issue #55 

### Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code or workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by davide-f** [comment]
Note: minimum python version has been updated as protobuf min version requires python 3.8

**Comment by davide-f** [comment]
@mnm-matin it would be great to agree on this and bump a new version 0.2.3 soon to then update the conda installation.
In conda, we have https://github.com/conda-forge/earth-osm-feedstock/pull/5 that fixes the changes of recipe/meta.yml but it is failing.

My advice is not to merge that PR to avoid having a breaking version into conda and skip 0.2.2 in conda.
When the new PR is triggered for v0.2.3 or 0.3, then we can use that as draft for the new version.

**Comment by mnm-matin** [comment]
lgtm. high quality pr 🚀🚀

**Comment by davide-f** [comment]
Many thanks :D I believe so.
The next step is try to prepare the new release v2.3 or v3 as you prefer and check if we experience issues with pip/conda installations

**Review by mnm-matin — APPROVED** [review]

**Comment by mnm-matin** [comment]
v2.3 sounds good!

**Comment by davide-f** [comment]
Many thanks :) merged, I'll prepare the release and check how it goes :)

**Comment by davide-f** [comment]
@mnm-matin Update: I've done as discussed and tried to release the new version.
The building works, but in the publishing there is an issue maybe related to permissions on PyPI?

Would be great your revision/comment/action here when you have time:
https://github.com/pypsa-meets-earth/earth-osm/issues/55#issuecomment-2538547180

Many thanks!

**Comment by davide-f** [comment]
@mnm-matin unfortunately we still have the issue with pypi and to avoid committing to test, it would be great to have better clarity on the options to push to pypi. I've added 2FA for pypi

**Pull request merged**
